name: Test Suite

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Checkout chrome-devtools-mcp
      uses: actions/checkout@v4
      with:
        repository: neurodance/chrome-devtools-mcp
        path: ../chrome-devtools-mcp

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable

    - name: Install dependencies
      run: |
        npm ci
        cd ../chrome-devtools-mcp && npm ci
        cd $GITHUB_WORKSPACE

    - name: Run linting
      run: npm run lint
      continue-on-error: true

    - name: Run unit tests
      run: npm test

    - name: Run integration tests
      run: npm run test:integration

    - name: Run visual regression tests
      run: npm run test:visual

    - name: Upload test artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts-${{ matrix.node-version }}
        path: |
          tests/snapshots/
          tests/results/

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/lcov.info
        flags: unittests
        name: codecov-${{ matrix.node-version }}
      continue-on-error: true

  test-jottr-io:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: jottr-io/package-lock.json

    - name: Install jottr-io dependencies
      working-directory: ./jottr-io
      run: npm ci

    - name: Run jottr-io tests
      working-directory: ./jottr-io
      run: npm test
      continue-on-error: true

    - name: Build jottr-io
      working-directory: ./jottr-io
      run: npm run build

  performance:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Install dependencies
      run: npm ci

    - name: Run performance tests
      run: |
        node -e "
        const puppeteer = require('puppeteer');
        (async () => {
          const browser = await puppeteer.launch();
          const page = await browser.newPage();
          await page.goto('file://${process.cwd()}/index.html');

          const metrics = await page.metrics();
          console.log('Performance Metrics:', metrics);

          const performanceTiming = JSON.parse(
            await page.evaluate(() => JSON.stringify(performance.timing))
          );

          const renderTime = performanceTiming.loadEventEnd - performanceTiming.fetchStart;
          console.log('Render time:', renderTime, 'ms');

          if (renderTime > 1000) {
            console.error('Performance regression: Render time exceeds 1000ms');
            process.exit(1);
          }

          await browser.close();
        })();
        "

  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run security audit
      run: npm audit --audit-level=high
      continue-on-error: true

    - name: Check for secrets
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD
      continue-on-error: true